[metadata]
name = tank-fill-modbus
version = 2026.05.19
description = A Modbus implementation for tank filling systems.
author = Bradley Lane Kicklighter, P.E.
author_email = blkickligh@usi.edu
url = https://github.com/blkickli/TankFillModbus
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE

[options]
